### ISSUE TITLE
about pycolorado pages

### ISSUE THREAD

**Issue by mjhea0** [PyColorado/pycolorado.org#8]
We need to add an "about" section on the PyColorado page that includes the following info:

1. General about PyColorado info
1. Code of Conduct
1. Why attend?
1. Venue Info
1. Organizer info

These may be separate pages. They could be lumped together. This issue should probably be broken up into separate issues.

**Comment by svvitale** [comment]
We've got most of these items resolved in one way or another.  Closing for now.  Will open more explicit issues if needed.
